name: Publish
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: |
          echo @govind:https://npm.pkg.github.com/ > build/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> build/.npmrc
      - run: npm publish
        working-directory: '.'
        env:
          NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}